---
- name: "Check for patroni_exporter binary"
  ansible.builtin.stat:
    path: '{{ patroni_exporter_install_dir }}/patroni_exporter.py'
  changed_when: false
  register: patroni_exporter_install

- name: "Install tasks"
  when: not patroni_exporter_install.stat.exists or patroni_exporter_force_install|bool
  block:
    - name: "REDHAT | Ensure EPEL is enabled"
      ansible.builtin.yum:
        name: epel-release
        state: present
      when: ansible_os_family == 'RedHat'

    - name: "Install requierements"
      ansible.builtin.package:
        name: '{{ patroni_packages }}'
        state: present

    - name: "Download patroni_exporter..."
      ansible.builtin.get_url:
        url: '{{ patroni_exporter_url }}'
        dest: '{{ patroni_exporter_install_dir }}'
        timeout: '60'
        mode: '0755'

- name: "Create systemd for patroni_exporter"
  ansible.builtin.template:
    src: 'patroni_exporter.service.j2'
    dest: '/etc/systemd/system/patroni_exporter.service'
    mode: '0640'
  notify: "restart patroni_exporter"

- name: "Enable and Start patroni_exporter.service"
  ansible.builtin.service:
    name: patroni_exporter
    state: started
    enabled: true
    daemon_reload: true
